### ISSUE TITLE
Modification In Readme File

### ISSUE THREAD

**Issue by codewithvk** [Code-Deeper/code-sync#110]
- [ ] Image Tour Of Entier application
- [x] Add License section In readme

**Comment by codewithvk** [comment]
@MadhuSaini22 You can look up this issue.

**Comment by MadhuSaini22** [comment]
@codewithvk  Can you please explain this "Image Tour of Entire application",
exactly what you want from here?

**Comment by codewithvk** [comment]
@MadhuSaini22 , If someone dosn't want to visit the website first or doesn't watch the video then they can get the idea by the image tour. Moreover, you need to take screenshots of every page to showcase what actually our project does. Put all images in ```assets``` folder and create one readme for Image Tour where you add all images with a one-line description.

If you still didn't understand, let me know i will help you for sure!

**Comment by MadhuSaini22** [comment]
Okay, I got it now.
I'll do it very soon;)
I want to ask you a question,
Can I became the member of Code-deeper? If so, then how!?

**Comment by codewithvk** [comment]
hey @MadhuSaini22 , As of now we don't hire employees but if you have an idea and wanna implement it in our project then we can think about that. Also if you don't have any idea still you can contribute and learn together our entire project is open source. You can send your resume at ```codedeeper.work@gmail.com``` with the title "Your favorite Tech - Github ID".

Thanks
