### ISSUE TITLE
Forgot Password with JWT

### ISSUE THREAD

**Issue by codewithvk** [Code-Deeper/code-sync#96]
- [x] Backend
- [x] Frontend

**Comment by iamrahulrnair** [comment]
hi, i would love to collaborate, if this issue is open, could you give a description of what needs to be done?

**Comment by codewithvk** [comment]
Hey @iamrahulrnair , Great to see you are interested in our project. Let me clarify what the problem statement is.

[ Description ] As of now in our app, there is no option to forget a password where if someone forgot password then they can't reset it. although there is a google option where you don't need any password. [ Technical Part ]  what we will do is we add one more column in the user modal for forgot password and we generate one tokenized link. That link will send via email ( NodeMailer) to users and when they click on the link they redirect one page with jwt argument where they can reset their password. also, we can modify further for JWT token valid for 48h/60h. 

This is my approach, If you have a better approach in terms of security & User reliability then it would be appreciable!

**Comment by iamrahulrnair** [comment]
This seems the standard approach, user clicks on link in mail with a valid time limit and redirects to a password reset page.
any constraints do i have to worry about like the token length and all?

**Comment by codewithvk** [comment]
Cool, Short token length will preferable.

**Comment by iamrahulrnair** [comment]
is there any client side endpoint for reset_password? i mean if the user recieves the mail where should the user go when he clicks the link?

**Comment by codewithvk** [comment]
@iamrahulrnair There is no route for forgot passwords. You want to build this feature from scratch. If you need any help let me know.

**Comment by iamrahulrnair** [comment]
> 

Yeah the thing is after getting the private url in mail, the user need a view for typing  the password and confirm password, then checking that and the jwt payload only the user can continue further, i was asking about that endpoint,
:-)

**Comment by codewithvk** [comment]
@iamrahulrnair No there is not an endpoint, You can create ```reset_password/:JWT``` for filling password. After update the password, you need to redirect them to the ```/login``` route so that they can log in with a new password. Hope you got it.

**Comment by iamrahulrnair** [comment]
hey @codewithvk , may i change the password hashing to a utility function, seems the code is repetitive and that too needed in the reset functionality, it will be better if this the case, lemme know your thought :-)

**Comment by codewithvk** [comment]
@iamrahulrnair Can describe broadly, What do you want to do?

**Comment by codewithvk** [comment]
Move To Jira 💯 
Automated Close

**Comment by iamrahulrnair** [comment]
> @iamrahulrnair Can you please describe broadly? What do you want to do?
See in here the hashing is  reused everywhere like , importing bcryptjs and doing hashing, when code base gets larger it will get complicated, so its better to create a utility function which returns a hash when password is given, so we don't have worry about the hash length and all, now we don't have to worry about this, will raise another issue for code refactoring and have discussion on that. :-)

I am done with server code for reset functionality, will raise a PR now.


![Screenshot from 2021-12-16 10-14-56](https://user-images.githubusercontent.com/55950758/146309891-9c8f8caf-e5fd-4ce9-82cb-03257aba1a85.png)
![Screenshot from 2021-12-16 10-15-14](https://user-images.githubusercontent.com/55950758/146309896-b753ec92-9f8b-4101-8b3d-405ce85f138b.png)

**Comment by codewithvk** [comment]
@iamrahulrnair Yup, You can create functions separately but functionality should be the same. And go ahead and rise a PR! 🥇

**Comment by iamrahulrnair** [comment]
> * [ ]  Frontend
> * [x]  Backend

Hey, i will work on the front end :-)

**Comment by iamrahulrnair** [comment]
Hey guys is this enough, since the feature is on low priority i haven't looked into it much  :-), and am not sure how the reset password page should be rendered, if a define a function component then everyone can access it right, so any idea how i should implement it?

![Screenshot from 2021-12-20 11-02-58](https://user-images.githubusercontent.com/55950758/146717057-ec91b8de-37d1-4251-a250-1d544b9ce67e.png)
![Screenshot from 2021-12-20 11-02-51](https://user-images.githubusercontent.com/55950758/146717063-ebd63273-0d8e-463b-bbc8-e7d4f28ad5c4.png)

**Comment by akshita-kamani** [comment]
> am not sure how the reset password page should be rendered, if a define a function component then everyone can access it right

@iamrahulrnair According to me, You can create separate component for Reset Password, and anyone can access it.mentioned screen-shots looks good for me, I will be change some UI after Your PR merged.

**Comment by codewithvk** [comment]
> am not sure how the reset password page should be rendered, if a define a function component then everyone can access it right, so any idea how i should implement it?

Hey, @iamrahulrnair . I am not getting your question? did you ask about render from loginpage.js? or something else.
> since the feature is on low priority i haven't looked into it much 

No worries brother, We are also busy in other stuff so that we can't do many contributions as of now :)

**Comment by iamrahulrnair** [comment]
> > am not sure how the reset password page should be rendered, if a define a function component then everyone can access it right, so any idea how i should implement it?
> 
> Hey, @iamrahulrnair . I am not getting your question? did you ask about render from loginpage.js? or something else.

No, After clicking on the link in mail, the user should go to a reset page, how should i render that page? What are things that i should consider ? If it is public everyone can access the route like '/reset_password/:JWT_KEY' , should i continue with this approach?

**Comment by codewithvk** [comment]
@iamrahulrnair You can make it public no worries Because we handle update password conditions by the backend. You can create ```/reset_password``` for sending the password to email and ```'/reset_password/:JWT``` for reset password and update. Hope you got my point.
